// <auto-generated />
using System;
using Legacy.Maliev.FileService.Data.CustomerDocuments;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legacy.Maliev.FileService.Data.Migrations.CustomerDocuments
{
    [DbContext(typeof(CustomerDocumentDbContext))]
    [Migration("20261008064021_InitialCustomerDocumentRegistry")]
    partial class InitialCustomerDocumentRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CustomerDocument", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerDocument_Customer", "\"CustomerId\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocument_Kind", "\"Kind\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_CustomerDocument_Revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocument_Visibility", "\"Visibility\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentLegalHold", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentId", "CustomerId");

                    b.ToTable("CustomerDocumentLegalHolds", (string)null);
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AssociationsSealed")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ContentSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ScanOperationId")
                        .HasColumnType("uuid");

                    b.Property<long>("ScanSourceGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("StorageGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageObjectName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("DocumentId", "CustomerId", "Kind");

                    b.ToTable("CustomerDocumentVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Actor", "length(btrim(\"ActorSubject\")) > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Filename", "length(btrim(\"OriginalFileName\")) > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Generation", "\"StorageGeneration\" > 0 AND \"ScanSourceGeneration\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Hash", "\"ContentSha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Kind", "\"Kind\" BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Number", "\"VersionNumber\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Scan", "\"ScanOperationId\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Size", "\"ContentSize\" BETWEEN 1 AND 20971520");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Storage", "length(btrim(\"StorageBucket\")) > 0 AND \"StorageObjectName\" = 'customer-documents/' || \"CustomerId\"::text || '/' || replace(\"DocumentId\"::text,'-','') || '/' || replace(\"Id\"::text,'-','') || '/original'");

                            t.HasCheckConstraint("CK_CustomerDocumentVersion_Type", "\"ContentType\" IN ('application/pdf','image/png','image/jpeg')");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentAssociation", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("VersionId", "Kind", "ResourceId");

                    b.HasIndex("VersionId")
                        .IsUnique()
                        .HasFilter("\"Kind\" = 2");

                    b.HasIndex("VersionId", "CustomerId");

                    b.ToTable("CustomerDocumentAssociation", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerDocumentAssociation_Customer", "\"Kind\" <> 0 OR \"ResourceId\" = \"CustomerId\"");

                            t.HasCheckConstraint("CK_CustomerDocumentAssociation_Id", "\"ResourceId\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentAssociation_Kind", "\"Kind\" BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("VersionId", "DocumentId");

                    b.ToTable("CustomerDocumentAudit", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerDocumentAudit_Actor", "length(btrim(\"ActorSubject\")) > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentAudit_Revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentVerificationEvidence", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedBySubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("VersionId", "Revision");

                    b.ToTable("CustomerDocumentVerificationEvidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomerDocumentVerificationEvidence_Revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("CK_CustomerDocumentVerificationEvidence_Status", "\"Status\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_CustomerDocumentVerificationEvidence_Verifier", "(\"Status\" = 0 AND \"VerifiedBySubject\" IS NULL AND \"VerifiedAtUtc\" IS NULL) OR (\"Status\" IN (1,2) AND \"VerifiedBySubject\" IS NOT NULL AND length(btrim(\"VerifiedBySubject\")) > 0 AND \"VerifiedAtUtc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.InternalNdaReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeadDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("NdaId")
                        .HasColumnType("uuid");

                    b.Property<long>("RenewalRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponsibleEmployeeSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleEmployeeSubject", "DueAtUtc");

                    b.HasIndex("NdaId", "VersionId", "RenewalRevision", "LeadDays")
                        .IsUnique();

                    b.HasIndex("NdaId", "VersionId", "RenewalRevision", "ResponsibleEmployeeSubject");

                    b.ToTable("InternalNdaReminder", null, t =>
                        {
                            t.HasCheckConstraint("CK_InternalNdaReminder_Lead", "\"LeadDays\" BETWEEN 0 AND 3660");

                            t.HasCheckConstraint("CK_InternalNdaReminder_Recipient", "length(btrim(\"ResponsibleEmployeeSubject\")) > 0");

                            t.HasCheckConstraint("CK_InternalNdaReminder_State", "\"State\" BETWEEN 0 AND 2 AND ((\"State\" = 2 AND \"CancelledAtUtc\" IS NOT NULL) OR (\"State\" <> 2 AND \"CancelledAtUtc\" IS NULL))");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaCoverage", b =>
                {
                    b.Property<Guid>("NdaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("NdaId", "Kind", "ResourceId");

                    b.HasIndex("NdaId", "CustomerId");

                    b.HasIndex("CustomerId", "Kind", "ResourceId");

                    b.ToTable("NdaCoverage", null, t =>
                        {
                            t.HasCheckConstraint("CK_NdaCoverage_Customer", "\"Kind\" <> 0 OR \"ResourceId\" = \"CustomerId\"");

                            t.HasCheckConstraint("CK_NdaCoverage_Identity", "\"ResourceId\" > 0 AND \"Kind\" BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CoverageSealed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartyOne")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PartyTwo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("RenewalAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponsibleEmployeeSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SupersedesNdaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SurvivalEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SurvivalKind")
                        .HasColumnType("integer");

                    b.Property<long>("VerificationRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedBySubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "VersionId", "VerificationRevision");

                    b.HasIndex("SupersedesNdaId")
                        .IsUnique()
                        .HasFilter("\"SupersedesNdaId\" IS NOT NULL");

                    b.HasIndex("DocumentId", "VerificationRevision")
                        .IsUnique();

                    b.HasIndex("VersionId", "CustomerId");

                    b.HasIndex("VersionId", "DocumentId");

                    b.HasIndex("VersionId", "VerificationRevision");

                    b.HasIndex("SupersedesNdaId", "DocumentId", "CustomerId");

                    b.ToTable("NdaRecord", null, t =>
                        {
                            t.HasCheckConstraint("CK_NdaRecord_Customer", "\"CustomerId\" > 0");

                            t.HasCheckConstraint("CK_NdaRecord_Dates", "(\"ExpiresAtUtc\" IS NULL OR \"ExpiresAtUtc\" > \"EffectiveAtUtc\") AND (\"RenewalAtUtc\" IS NULL OR \"RenewalAtUtc\" >= \"EffectiveAtUtc\")");

                            t.HasCheckConstraint("CK_NdaRecord_Parties", "length(btrim(\"PartyOne\")) > 0 AND length(btrim(\"PartyTwo\")) > 0 AND lower(btrim(\"PartyOne\")) <> lower(btrim(\"PartyTwo\"))");

                            t.HasCheckConstraint("CK_NdaRecord_Revision", "\"VerificationRevision\" > 0");

                            t.HasCheckConstraint("CK_NdaRecord_Staff", "length(btrim(\"ResponsibleEmployeeSubject\")) > 0 AND length(btrim(\"VerifiedBySubject\")) > 0");

                            t.HasCheckConstraint("CK_NdaRecord_Survival", "(\"SurvivalKind\" IN (0,1) AND \"SurvivalEndsAtUtc\" IS NULL) OR (\"SurvivalKind\" = 2 AND \"SurvivalEndsAtUtc\" IS NOT NULL AND \"SurvivalEndsAtUtc\" >= COALESCE(\"ExpiresAtUtc\",\"EffectiveAtUtc\"))");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.ProtectedDocumentUploadCheckpoint", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CompletedRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("VersionId")
                        .IsUnique();

                    b.HasIndex("DocumentId", "CustomerId");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId", "Subject", "KeyHash")
                        .IsUnique();

                    b.ToTable("CustomerDocumentUploadCheckpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentUpload_Completed", "(\"State\" = 'Completed' AND \"CompletedRevision\" IS NOT NULL AND \"CompletedRevision\" > 0) OR (\"State\" <> 'Completed' AND \"CompletedRevision\" IS NULL)");

                            t.HasCheckConstraint("CK_DocumentUpload_Scope", "\"CustomerId\" > 0 AND \"VersionNumber\" > 0");

                            t.HasCheckConstraint("CK_DocumentUpload_State", "\"State\" IN ('Pending','Unknown','Completed')");
                        });
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentLegalHold", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "CustomerId", "Kind")
                        .HasPrincipalKey("Id", "CustomerId", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentAssociation", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentAudit", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "DocumentId")
                        .HasPrincipalKey("Id", "DocumentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentVerificationEvidence", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.InternalNdaReminder", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaRecord", null)
                        .WithMany()
                        .HasForeignKey("NdaId", "VersionId", "RenewalRevision", "ResponsibleEmployeeSubject")
                        .HasPrincipalKey("Id", "VersionId", "VerificationRevision", "ResponsibleEmployeeSubject")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaCoverage", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaRecord", null)
                        .WithMany()
                        .HasForeignKey("NdaId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaRecord", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "DocumentId")
                        .HasPrincipalKey("Id", "DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.DocumentVerificationEvidence", null)
                        .WithMany()
                        .HasForeignKey("VersionId", "VerificationRevision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.NdaRecord", null)
                        .WithMany()
                        .HasForeignKey("SupersedesNdaId", "DocumentId", "CustomerId")
                        .HasPrincipalKey("Id", "DocumentId", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Legacy.Maliev.FileService.Domain.CustomerDocuments.ProtectedDocumentUploadCheckpoint", b =>
                {
                    b.HasOne("Legacy.Maliev.FileService.Domain.CustomerDocuments.CustomerDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "CustomerId")
                        .HasPrincipalKey("Id", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
